-- Game client UI strings (English default in `text`, Italian `text_it`, Portuguese `text_pt`).
-- Frontend resolves by `tag`. Placeholders: {name}, {item}, {status}, {others}, {wilds}, {npcs}, {zone}, {x}, {z}, {id}, {turn}, {description}
-- Run once; adjust id_language_text / dt_c as needed.

INSERT INTO playanimaster_db.language_texts (dt_c, tag, text, text_it, text_pt) VALUES
(NOW(), 'ui.loading', 'Loading…', 'Caricamento…', 'A carregar…'),
(NOW(), 'ui.back', 'Back', 'Indietro', 'Voltar'),
(NOW(), 'ui.close', 'Close', 'Chiudi', 'Fechar'),
(NOW(), 'ui.save', 'Save', 'Salva', 'Guardar'),
(NOW(), 'ui.cancel', 'Cancel', 'Annulla', 'Cancelar'),
(NOW(), 'ui.ok', 'OK', 'OK', 'OK'),
(NOW(), 'ui.use', 'Use', 'Usa', 'Usar'),
(NOW(), 'ui.next', 'Next', 'Avanti', 'Seguinte'),
(NOW(), 'ui.combat_close_title', 'Only after battle ends', 'Solo a fine lotta', 'Só após o fim da batalha'),

(NOW(), 'combat.title', 'Combat', 'Lotta', 'Combate'),
(NOW(), 'combat.flee', 'Flee', 'Fuga', 'Fugir'),
(NOW(), 'combat.fight', 'Fight', 'Combatti', 'Lutar'),
(NOW(), 'combat.fight_hint', 'Select an ability to attack.', 'Scegli un''abilità per attaccare.', 'Escolhe uma habilidade para atacar.'),
(NOW(), 'combat.items', 'Items', 'Oggetti', 'Itens'),
(NOW(), 'combat.items_hint', 'Use an item on your team.', 'Usa un oggetto sulla squadra.', 'Usa um item na tua equipa.'),
(NOW(), 'combat.team', 'Team', 'Squadra', 'Equipa'),
(NOW(), 'combat.team_hint', 'Switch to another creature.', 'Cambia creatura.', 'Troca de criatura.'),
(NOW(), 'combat.choose_action', 'Choose an action.', 'Scegli un''azione.', 'Escolhe uma ação.'),
(NOW(), 'combat.choose_ability', 'Choose an ability or flee.', 'Scegli un''abilità o fuggi.', 'Escolhe uma habilidade ou foge.'),
(NOW(), 'combat.choose_item', 'Choose an item.', 'Scegli un oggetto.', 'Escolhe um item.'),
(NOW(), 'combat.choose_switch', 'Choose a creature to switch in.', 'Scegli la creatura da mandare in campo.', 'Escolhe a criatura para entrar em campo.'),
(NOW(), 'combat.loading_turn', 'Loading turn…', 'Caricamento turno…', 'A carregar turno…'),
(NOW(), 'combat.resolving_turn', 'Resolving turn…', 'Risoluzione turno…', 'A resolver turno…'),
(NOW(), 'combat.load_failed', 'Combat load failed', 'Caricamento lotta fallito', 'Falha ao carregar combate'),
(NOW(), 'combat.no_battle_data', 'No battle data.', 'Nessun dato di lotta.', 'Sem dados de batalha.'),
(NOW(), 'combat.no_battle_data_turn', 'No battle data for this turn. Close (×) to exit.', 'Nessun dato per questo turno. Chiudi (×) per uscire.', 'Sem dados para este turno. Fecha (×) para sair.'),
(NOW(), 'combat.action_failed', 'Action failed', 'Azione fallita', 'Ação falhou'),
(NOW(), 'combat.status_victory', 'Victory! The wild animal was freed.', 'Vittoria! L''animale selvatico è stato liberato.', 'Vitória! O animal selvagem foi libertado.'),
(NOW(), 'combat.status_defeat', 'You have no usable creatures. You blacked out.', 'Non hai creature utilizzabili. Sei svenuto.', 'Não tens criaturas utilizáveis. Desmaiaste.'),
(NOW(), 'combat.status_fled', 'You fled from battle.', 'Sei fuggito dalla lotta.', 'Fugiste da batalha.'),
(NOW(), 'combat.status_ended', 'Battle ended: {status}', 'Lotta terminata: {status}', 'Batalha terminada: {status}'),
(NOW(), 'combat.status_blackout_loading', 'You have no usable creatures. You blacked out…', 'Non hai creature utilizzabili. Sei svenuto…', 'Não tens criaturas utilizáveis. Desmaiaste…'),
(NOW(), 'combat.recovery_failed', 'Recovery failed. Close (×) to continue.', 'Recupero fallito. Chiudi (×) per continuare.', 'Recuperação falhou. Fecha (×) para continuar.'),
(NOW(), 'combat.loading_abilities', 'Loading abilities…', 'Caricamento abilità…', 'A carregar habilidades…'),
(NOW(), 'combat.no_abilities', 'No abilities available.', 'Nessuna abilità disponibile.', 'Nenhuma habilidade disponível.'),
(NOW(), 'combat.load_abilities_failed', 'Could not load abilities', 'Impossibile caricare le abilità', 'Não foi possível carregar habilidades'),
(NOW(), 'combat.loading_items', 'Loading items…', 'Caricamento oggetti…', 'A carregar itens…'),
(NOW(), 'combat.no_items', 'No usable items in battle.', 'Nessun oggetto utilizzabile in lotta.', 'Nenhum item utilizável em combate.'),
(NOW(), 'combat.load_items_failed', 'Could not load items', 'Impossibile caricare gli oggetti', 'Não foi possível carregar itens'),
(NOW(), 'combat.loading_team', 'Loading team…', 'Caricamento squadra…', 'A carregar equipa…'),
(NOW(), 'combat.load_team_failed', 'Could not load team', 'Impossibile caricare la squadra', 'Não foi possível carregar equipa'),
(NOW(), 'combat.no_switch_targets', 'No other team creatures available.', 'Nessun''altra creatura in squadra disponibile.', 'Nenhuma outra criatura da equipa disponível.'),
(NOW(), 'combat.item_target_prompt', 'Use {item} on which creature?', 'Su quale creatura usare {item}?', 'Em que criatura usar {item}?'),
(NOW(), 'combat.no_item_target', 'No valid target for this item.', 'Nessun bersaglio valido per questo oggetto.', 'Nenhum alvo válido para este item.'),
(NOW(), 'combat.unit_your_animal', 'Your animal', 'La tua creatura', 'A tua criatura'),
(NOW(), 'combat.unit_wild', 'Wild', 'Selvatico', 'Selvagem'),
(NOW(), 'combat.log_turn', 'T{turn}: {description}', 'T{turn}: {description}', 'T{turn}: {description}'),
(NOW(), 'combat.press_space_continue', 'Press Space to continue…', 'Premi Spazio per continuare…', 'Prime Espaço para continuar…'),
(NOW(), 'combat.auto_advance', 'Auto-advance', 'Avanzamento automatico', 'Avanço automático'),
(NOW(), 'combat.missed', 'But it missed!', 'Ma non l''ha preso!', 'Mas falhou!'),
(NOW(), 'combat.hit', 'Hit!', 'Preso!', 'Acertou!'),
(NOW(), 'combat.critical_hit', 'Critical hit!', 'Preso in pieno!', 'Acertou em cheio!'),
(NOW(), 'combat.stat_attack', 'attack', 'attacco', 'ataque'),
(NOW(), 'combat.stat_defense', 'defense', 'difesa', 'defesa'),
(NOW(), 'combat.stat_matk', 'magic attack', 'attacco magico', 'ataque mágico'),
(NOW(), 'combat.stat_mdef', 'magic defense', 'difesa magica', 'defesa mágica'),
(NOW(), 'combat.stat_accuracy', 'accuracy', 'precisione', 'pontaria'),
(NOW(), 'combat.stat_evasion', 'evasion', 'evasione', 'evasão'),
(NOW(), 'combat.stat_critical', 'critical rate', 'probabilità critica', 'probabilidade crítica'),
(NOW(), 'combat.stat_speed', 'speed', 'velocità', 'velocidade'),
(NOW(), 'combat.stat_increased', 'increased', 'è aumentato', 'aumentou'),
(NOW(), 'combat.stat_decreased', 'decreased', 'è diminuito', 'diminuiu'),
(NOW(), 'combat.stat_changed', '{name}''s {stat} {direction}.', '{stat} di {name} {direction}.', 'O {stat} de {name} {direction}.'),

(NOW(), 'dialog.talk_button', 'Talk [Space]', 'Parla [Spazio]', 'Falar [Espaço]'),
(NOW(), 'dialog.choose_topic', 'Choose a topic', 'Scegli un argomento', 'Escolhe um tema'),
(NOW(), 'dialog.choose_topic_prompt', 'What would you like to talk about?', 'Di cosa vorresti parlare?', 'Sobre o que gostarias de falar?'),
(NOW(), 'dialog.npc_fallback', 'NPC', 'PNG', 'NPC'),
(NOW(), 'dialog.conversation_fallback', 'Conversation {id}', 'Conversazione {id}', 'Conversa {id}'),
(NOW(), 'dialog.option_fallback', 'Option {id}', 'Opzione {id}', 'Opção {id}'),

(NOW(), 'hud.help', 'WASD move · Walk into wilds to battle · Talk to NPCs · I bag · T team', 'WASD muovi · Avvicinati ai selvatici per lottare · Parla con PNG · I borsa · T squadra', 'WASD mover · Aproxima-te de selvagens para combater · Falar com NPCs · I mochila · T equipa'),
(NOW(), 'hud.team', 'Team', 'Squadra', 'Equipa'),
(NOW(), 'hud.bag', 'Bag', 'Borsa', 'Mochila'),
(NOW(), 'hud.characters', 'Characters', 'Personaggi', 'Personagens'),
(NOW(), 'hud.logout', 'Logout', 'Esci', 'Sair'),
(NOW(), 'hud.status_counts', 'Others: {others} · Wild: {wilds} · NPC: {npcs}', 'Altri: {others} · Selvatici: {wilds} · PNG: {npcs}', 'Outros: {others} · Selvagens: {wilds} · NPCs: {npcs}'),
(NOW(), 'hud.player_position', '{name} · Zone {zone} · ({x}, {z})', '{name} · Zona {zone} · ({x}, {z})', '{name} · Zona {zone} · ({x}, {z})'),
(NOW(), 'hud.default_player', 'Player', 'Giocatore', 'Jogador'),
(NOW(), 'hud.default_you', 'You', 'Tu', 'Tu'),

(NOW(), 'inventory.title', 'Inventory', 'Inventario', 'Inventário'),
(NOW(), 'inventory.empty', 'Your bag is empty.', 'La borsa è vuota.', 'A mochila está vazia.'),
(NOW(), 'inventory.load_failed', 'Could not load inventory.', 'Impossibile caricare l''inventario.', 'Não foi possível carregar inventário.'),
(NOW(), 'inventory.no_items', 'No items', 'Nessun oggetto', 'Sem itens'),
(NOW(), 'inventory.select_item', 'Select an item from the list.', 'Seleziona un oggetto dall''elenco.', 'Seleciona um item da lista.'),
(NOW(), 'inventory.item_fallback', 'Item {id}', 'Oggetto {id}', 'Item {id}'),
(NOW(), 'inventory.meta_effect', 'Effect: {effect}', 'Effetto: {effect}', 'Efeito: {effect}'),
(NOW(), 'inventory.meta_usable_on', 'Use on: {target}', 'Usa su: {target}', 'Usar em: {target}'),
(NOW(), 'inventory.cannot_use_here', 'This item cannot be used here.', 'Questo oggetto non può essere usato qui.', 'Este item não pode ser usado aqui.'),
(NOW(), 'inventory.team_picker_title', 'Use on which animal?', 'Su quale animale?', 'Em que animal?'),
(NOW(), 'inventory.no_team_animals', 'You have no team animals.', 'Non hai animali in squadra.', 'Não tens animais na equipa.'),
(NOW(), 'inventory.cannot_use_on_animal', 'You cannot use this item on that animal.', 'Non puoi usare questo oggetto su quell''animale.', 'Não podes usar este item nesse animal.'),
(NOW(), 'inventory.using_item', 'Using item…', 'Uso oggetto…', 'A usar item…'),
(NOW(), 'inventory.item_used', 'Item used on {name}.', 'Oggetto usato su {name}.', 'Item usado em {name}.'),
(NOW(), 'inventory.use_failed', 'Could not use item.', 'Impossibile usare l''oggetto.', 'Não foi possível usar item.'),

(NOW(), 'team.title', 'Team', 'Squadra', 'Equipa'),
(NOW(), 'team.empty', 'Your team is empty.', 'La squadra è vuota.', 'A equipa está vazia.'),
(NOW(), 'team.load_failed', 'Could not load team.', 'Impossibile caricare la squadra.', 'Não foi possível carregar equipa.'),
(NOW(), 'team.no_animals', 'No team animals', 'Nessun animale in squadra', 'Sem animais na equipa'),
(NOW(), 'team.nickname_label', 'Nickname', 'Soprannome', 'Alcunha'),
(NOW(), 'team.level_prefix', 'Level {level}', 'Livello {level}', 'Nível {level}'),
(NOW(), 'team.lv_short', 'Lv.{level}', 'Lv.{level}', 'Nv.{level}'),
(NOW(), 'team.element_prefix', 'Element: {element}', 'Elemento: {element}', 'Elemento: {element}'),
(NOW(), 'team.fainted', '(fainted)', '(svenuto)', '(desmaiado)'),
(NOW(), 'team.saving_nickname', 'Saving nickname…', 'Salvataggio soprannome…', 'A guardar alcunha…'),
(NOW(), 'team.nickname_saved', 'Nickname saved.', 'Soprannome salvato.', 'Alcunha guardada.'),
(NOW(), 'team.nickname_save_failed', 'Could not save nickname.', 'Impossibile salvare il soprannome.', 'Não foi possível guardar alcunha.'),
(NOW(), 'team.animal_fallback', 'Animal {id}', 'Animale {id}', 'Animal {id}'),
(NOW(), 'team.species_fallback', 'Species {id}', 'Specie {id}', 'Espécie {id}'),

(NOW(), 'world.wild_fallback', 'Wild #{id}', 'Selvatico #{id}', 'Selvagem #{id}'),
(NOW(), 'world.other_player_fallback', 'Player', 'Giocatore', 'Jogador'),

(NOW(), 'target.type_self', 'Your character', 'Il tuo personaggio', 'O teu personagem'),
(NOW(), 'target.type_player', 'Player', 'Giocatore', 'Jogador'),
(NOW(), 'target.type_npc', 'NPC', 'NPC', 'NPC'),
(NOW(), 'target.type_wild', 'Wild animal', 'Animale selvatico', 'Animal selvagem'),

(NOW(), 'stats.hp_value', '{current} / {max} HP', '{current} / {max} PS', '{current} / {max} HP'),

(NOW(), 'error.start_battle_failed', 'Could not start battle', 'Impossibile iniziare la lotta', 'Não foi possível iniciar batalha');

-- Chat UI strings: see language_texts_chat.sql for incremental INSERT.
 