-- Chat UI strings for language_texts.
-- Run once on playanimaster_db (safe to re-run only if tags do not exist yet).

INSERT INTO playanimaster_db.language_texts (dt_c, tag, text, text_it, text_pt) VALUES
(NOW(), 'chat.title', 'Chat', 'Chat', 'Chat'),
(NOW(), 'chat.send', 'Send', 'Invia', 'Enviar'),
(NOW(), 'chat.empty', 'No messages in this tab.', 'Nessun messaggio in questa scheda.', 'Sem mensagens neste separador.'),
(NOW(), 'chat.input_placeholder', 'Message… @name · !zone · $clan · #party · %alliance · *global', 'Messaggio… @nome · !zona · $clan · #party · %alleanza · *globale', 'Mensagem… @nome · !zona · $clã · #party · %aliança · *global'),
(NOW(), 'chat.whisper_new_player', '@ New player…', '@ Nuovo giocatore…', '@ Novo jogador…'),
(NOW(), 'chat.position_toggle', 'Move chat left / right', 'Sposta chat a sinistra / destra', 'Mover chat esquerda / direita'),
(NOW(), 'chat.collapse', 'Collapse chat', 'Comprimi chat', 'Recolher chat'),
(NOW(), 'chat.expand', 'Expand chat', 'Espandi chat', 'Expandir chat'),
(NOW(), 'chat.minimize_icon', 'Minimize to icon', 'Riduci a icona', 'Minimizar para ícone'),
(NOW(), 'chat.restore_from_icon', 'Open chat', 'Apri chat', 'Abrir chat'),
(NOW(), 'chat.settings_open', 'Channel filters for this tab', 'Filtri canale per questa scheda', 'Filtros de canal para este separador'),
(NOW(), 'chat.settings_close', 'Done', 'Fatto', 'Concluído'),
(NOW(), 'chat.settings_title', 'Show in {tab}', 'Mostra in {tab}', 'Mostrar em {tab}'),
(NOW(), 'chat.tab_main', 'Main', 'Principale', 'Principal'),
(NOW(), 'chat.tab_whisper', 'Whisper', 'Sussurro', 'Sussurro'),
(NOW(), 'chat.tab_zone', 'Zone', 'Zona', 'Zona'),
(NOW(), 'chat.tab_clan', 'Clan', 'Clan', 'Clã'),
(NOW(), 'chat.tab_party', 'Party', 'Party', 'Party'),
(NOW(), 'chat.tab_alliance', 'Alliance', 'Alleanza', 'Aliança'),
(NOW(), 'chat.tab_global', 'Global', 'Globale', 'Global'),
(NOW(), 'chat.channel_local', 'Local', 'Locale', 'Local'),
(NOW(), 'chat.channel_whisper', 'Whisper', 'Sussurro', 'Sussurro'),
(NOW(), 'chat.channel_zone', 'Zone', 'Zona', 'Zona'),
(NOW(), 'chat.channel_clan', 'Clan', 'Clan', 'Clã'),
(NOW(), 'chat.channel_party', 'Party', 'Party', 'Party'),
(NOW(), 'chat.channel_alliance', 'Alliance', 'Alleanza', 'Aliança'),
(NOW(), 'chat.channel_global', 'Global', 'Globale', 'Global'),
(NOW(), 'chat.error_empty_message', 'Message cannot be empty.', 'Il messaggio non può essere vuoto.', 'A mensagem não pode estar vazia.'),
(NOW(), 'chat.error_too_long', 'Message is too long.', 'Messaggio troppo lungo.', 'Mensagem demasiado longa.'),
(NOW(), 'chat.error_whisper_invalid', 'Invalid whisper format. Use @Name message', 'Formato sussurro non valido. Usa @Nome messaggio', 'Formato de sussurro inválido. Usa @Nome mensagem'),
(NOW(), 'chat.error_whisper_no_message', 'Whisper needs a message after the name.', 'Il sussurro richiede un messaggio dopo il nome.', 'O sussurro precisa de uma mensagem após o nome.'),
(NOW(), 'chat.error_whisper_not_found', 'Player not found.', 'Giocatore non trovato.', 'Jogador não encontrado.'),
(NOW(), 'chat.error_whisper_offline', 'That player is offline.', 'Quel giocatore è offline.', 'Esse jogador está offline.'),
(NOW(), 'chat.error_no_clan', 'You are not in a clan.', 'Non sei in un clan.', 'Não estás num clã.'),
(NOW(), 'chat.error_no_party', 'You are not in a party.', 'Non sei in un party.', 'Não estás numa party.'),
(NOW(), 'chat.error_no_alliance', 'You are not in an alliance.', 'Non sei in un''alleanza.', 'Não estás numa aliança.'),
(NOW(), 'chat.error_no_global_pass', 'You need a global chat pass.', 'Serve un pass per la chat globale.', 'Precisas de um passe para o chat global.'),
(NOW(), 'chat.error_invalid_sender', 'Could not send message.', 'Impossibile inviare il messaggio.', 'Não foi possível enviar mensagem.'),
(NOW(), 'chat.error_server_error', 'Chat is temporarily unavailable. Try again later.', 'Chat temporaneamente non disponibile. Riprova più tardi.', 'Chat temporariamente indisponível. Tenta mais tarde.'),
(NOW(), 'chat.error_generic', 'Could not send message.', 'Impossibile inviare il messaggio.', 'Não foi possível enviar mensagem.');
