-- PvP 1v1 duel system (ANIMASTER)
-- Run once on playanimaster_db.

CREATE TABLE IF NOT EXISTS playanimaster_db.pvp_duel_requests (
    id_duel_request INT(11) NOT NULL AUTO_INCREMENT,
    id_user_ig_challenger INT(11) NOT NULL,
    id_user_ig_target INT(11) NOT NULL,
    id_zone INT(11) NOT NULL,
    dt_c TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    dt_expires DATETIME NOT NULL,
    flg_status CHAR(1) NOT NULL DEFAULT 'P' COMMENT 'P=pending, A=accepted, D=declined, X=expired, C=cancelled',
    dt_m TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id_duel_request),
    KEY idx_duel_req_target_pending (id_user_ig_target, flg_status, dt_expires),
    KEY idx_duel_req_challenger_pending (id_user_ig_challenger, flg_status, dt_expires)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS playanimaster_db.battles_pvp (
    id_battle_pvp INT(11) NOT NULL AUTO_INCREMENT,
    id_duel_request INT(11) DEFAULT NULL,
    id_user_ig_a INT(11) NOT NULL COMMENT 'Challenger',
    id_user_ig_b INT(11) NOT NULL COMMENT 'Target',
    id_zone INT(11) DEFAULT NULL,
    flg_status CHAR(1) NOT NULL DEFAULT 'O' COMMENT 'O=ongoing, F=finished, X=cancelled',
    id_winner_user_ig INT(11) DEFAULT NULL,
    end_reason VARCHAR(50) DEFAULT NULL,
    awaiting_user_ig INT(11) DEFAULT NULL,
    current_turn INT(11) NOT NULL DEFAULT 0,
    dt_c TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    dt_finished TIMESTAMP NULL DEFAULT NULL,
    dt_m TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id_battle_pvp),
    KEY idx_battles_pvp_user_a (id_user_ig_a, flg_status),
    KEY idx_battles_pvp_user_b (id_user_ig_b, flg_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS playanimaster_db.battles_pvp_moves (
    id_battle_pvp_move INT(11) NOT NULL AUTO_INCREMENT,
    id_battle_pvp INT(11) DEFAULT NULL,
    id_user_ig_actor INT(11) DEFAULT NULL,
    dt_creazione TIMESTAMP NULL DEFAULT NULL,
    dt_modifica TIMESTAMP NULL DEFAULT NULL,
    turn INT(11) DEFAULT NULL,
    move_type VARCHAR(100) DEFAULT NULL,
    move_speed DECIMAL(10,2) DEFAULT NULL,
    order_in_turn INT(11) DEFAULT NULL,
    id_rif INT(11) DEFAULT NULL,
    move_description VARCHAR(200) DEFAULT NULL,
    move_hit VARCHAR(1) DEFAULT NULL,
    w_a_res_hp INT(11) DEFAULT NULL,
    p_a_res_hp INT(11) DEFAULT NULL,
    w_a_res_atk DECIMAL(10,2) DEFAULT NULL,
    w_a_res_def DECIMAL(10,2) DEFAULT NULL,
    w_a_res_matk DECIMAL(10,2) DEFAULT NULL,
    w_a_res_mdef DECIMAL(10,2) DEFAULT NULL,
    w_a_res_acc INT(11) DEFAULT NULL,
    w_a_res_eva INT(11) DEFAULT NULL,
    w_a_res_cr INT(11) DEFAULT NULL,
    w_a_res_spd DECIMAL(10,2) DEFAULT NULL,
    p_a_res_atk DECIMAL(10,2) DEFAULT NULL,
    p_a_res_def DECIMAL(10,2) DEFAULT NULL,
    p_a_res_matk DECIMAL(10,2) DEFAULT NULL,
    p_a_res_mdef DECIMAL(10,2) DEFAULT NULL,
    p_a_res_acc INT(11) DEFAULT NULL,
    p_a_res_eva INT(11) DEFAULT NULL,
    p_a_res_cr INT(11) DEFAULT NULL,
    p_a_res_spd DECIMAL(10,2) DEFAULT NULL,
    w_a_res_max_hp INT(11) DEFAULT NULL,
    p_a_res_max_hp INT(11) DEFAULT NULL,
    protagonist_type VARCHAR(100) DEFAULT NULL,
    id_protagonist INT(11) DEFAULT NULL,
    target_type VARCHAR(100) DEFAULT NULL,
    id_target INT(11) DEFAULT NULL,
    w_a_id INT(11) DEFAULT NULL,
    w_a_id_species INT(11) DEFAULT NULL,
    w_a_species VARCHAR(100) DEFAULT NULL,
    w_a_lvl INT(11) DEFAULT NULL,
    p_a_id INT(11) DEFAULT NULL,
    p_a_id_species INT(11) DEFAULT NULL,
    p_a_species VARCHAR(100) DEFAULT NULL,
    p_a_lvl INT(11) DEFAULT NULL,
    p_a_nickname VARCHAR(100) DEFAULT NULL,
    resulting_battle_status VARCHAR(10) DEFAULT NULL,
    w_a_id_element INT(11) DEFAULT NULL,
    p_a_id_element INT(11) DEFAULT NULL,
    p_a_cur_exp INT(11) DEFAULT '0',
    PRIMARY KEY (id_battle_pvp_move),
    KEY idx_battles_pvp_moves_battle (id_battle_pvp, turn)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS playanimaster_db.pvp_turn_choices (
    id_turn_choice INT(11) NOT NULL AUTO_INCREMENT,
    id_battle_pvp INT(11) NOT NULL,
    turn INT(11) NOT NULL,
    id_user_ig INT(11) NOT NULL,
    action_type VARCHAR(50) NOT NULL,
    action_id INT(11) NOT NULL DEFAULT 0,
    dt_c TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id_turn_choice),
    UNIQUE KEY uniq_pvp_turn_choice (id_battle_pvp, turn, id_user_ig),
    KEY idx_pvp_turn_choice_battle (id_battle_pvp, turn)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


INSERT INTO playanimaster_db.language_texts (dt_c, tag, text, text_it, text_pt) VALUES
(NOW(), 'duel.request_tooltip', 'Duel', 'Duello', 'Duelo'),
(NOW(), 'duel.request_sent', 'Duel challenge sent.', 'Sfida al duello inviata.', 'Desafio de duelo enviado.'),
(NOW(), 'duel.request_failed', 'Could not send duel challenge.', 'Impossibile inviare la sfida.', 'Não foi possível enviar o desafio.'),
(NOW(), 'duel.incoming_title', '{name} challenges you to a duel', '{name} ti sfida a duello', '{name} desafia-te para um duelo'),
(NOW(), 'duel.accept', 'Accept', 'Accetta', 'Aceitar'),
(NOW(), 'duel.decline', 'Decline', 'Rifiuta', 'Recusar'),
(NOW(), 'duel.expired', 'Duel challenge expired.', 'Sfida al duello scaduta.', 'Desafio de duelo expirado.'),
(NOW(), 'duel.waiting', 'Waiting for {name}…', 'In attesa di {name}…', 'À espera de {name}…'),
(NOW(), 'duel.waiting_opponent', 'Opponent is choosing…', 'L''avversario sta scegliendo…', 'O adversário está a escolher…'),
(NOW(), 'duel.waiting_resolve', 'Waiting for both choices…', 'In attesa delle scelte…', 'À espera das escolhas…'),
(NOW(), 'duel.choice_locked', 'Choice locked — waiting for opponent.', 'Scelta registrata — in attesa dell''avversario.', 'Escolha registada — à espera do adversário.'),
(NOW(), 'duel.opponent_ready', 'Opponent locked in — choose your action.', 'L''avversario ha scelto — scegli la tua azione.', 'O adversário escolheu — escolhe a tua ação.'),
(NOW(), 'duel.error_offline', 'Player is not available.', 'Giocatore non disponibile.', 'Jogador indisponível.'),
(NOW(), 'duel.error_busy', 'You or the other player are busy.', 'Tu o l''altro giocatore siete occupati.', 'Tu ou o outro jogador estão ocupados.'),
(NOW(), 'duel.error_range', 'Player is too far away.', 'Giocatore troppo lontano.', 'Jogador demasiado longe.'),
(NOW(), 'duel.error_no_team', 'You need at least one animal with HP to duel.', 'Serve almeno un animale con HP per duellare.', 'Precisas de pelo menos um animal com HP para duelar.'),
(NOW(), 'duel.error_cooldown', 'Wait before challenging this player again.', 'Attendi prima di sfidare di nuovo questo giocatore.', 'Espera antes de desafiar este jogador novamente.'),
(NOW(), 'duel.error_generic', 'Duel failed.', 'Duello fallito.', 'Duelo falhou.'),
(NOW(), 'duel.win', 'You won the duel!', 'Hai vinto il duello!', 'Ganhaste o duelo!'),
(NOW(), 'duel.lose', 'You lost the duel.', 'Hai perso il duello.', 'Perdeste o duelo.'),
(NOW(), 'duel.opponent_label', 'Opponent', 'Avversario', 'Adversário'),
(NOW(), 'combat.pvp_your_turn', 'Choose an action.', 'Scegli un''azione.', 'Escolhe uma ação.');
